#!/bin/sh
docker node demote $( docker node ls | grep -i reachable | cut -d' ' -f1 )
docker node rm $( docker node ls -q | grep -v $(docker info -f {{.Swarm.NodeID}}) )
docker-compose kill
docker-compose rm -f

# docker swarm leave -f