version: '3.2'

services:
  cluster:
    image: consul:latest
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      labels:
        traefik.frontend.rule: PathPrefix:/ui/,/v1/
        traefik.port: 8500
        traefik.docker.network: swarmtools_proxy
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true, "disable_update_check": true}'
      CONSUL_BIND_INTERFACE: eth0
    command:
    - agent
    - -server
    - -retry-join=cluster
    - -bootstrap-expect=3
    - -ui
    - -disable-host-node-id
    - -client=0.0.0.0
    - -data-dir=/consul/data
    networks:
    - consul
    - swarmtools_proxy

networks:
  consul:
  swarmtools_proxy:
    external: true
